#!/bin/bash

SERVER_NAME=${SERVER_NAME-"minecraft-server"}
SERVER_PORT=${SERVER_PORT-"25565"}
BACKUP_INTERVAL=${BACKUP_INTERVAL-"360"} # Every 6 h
AUTH_SERVER_URL=${MINECRAFT_AUTH_SERVER_URL-"https://auth.craftorio.com"}

function info {
    printf "\033[0;36m${1}\033[0m \n"
}
function note {
    printf "\033[0;33m${1}\033[0m \n"
}
function success {
    printf "\033[0;32m${1}\033[0m \n"
}
function warning {
    printf "\033[0;95m${1}\033[0m \n"
}
function error {
    printf "\033[0;31m${1}\033[0m \n"
    exit 1
}

while [[ $# > 1 ]]
do
key="$1"
case ${key} in
    -a|--auth-server-url)
    AUTH_SERVER_URL="$2"
    shift
    ;;
    -d|--data)
    DATA_DIR="$2"
    shift
    ;;
    -n|--name)
    SERVER_NAME="$2"
    shift
    ;;
    -i|--image)
    CONTAINER_IMAGE="$2"
    shift
    ;;
    -p|--port)
    SERVER_PORT="$2"
    ;;
    --dynmap-port)
    DYNMAP_PORT="$2"
    shift
    ;;
    -c|--cpu-count)
    MC_CPU_COUNT="$2"
    shift
    ;;
    -im|--init-memory)
    MC_INIT_MEMORY="$2"
    shift
    ;;
    -mm|--max-memory)
    MC_MAX_MEMORY="$2"
    shift
    ;;
    --s3-key)
    S3_ACCESS_KEY="$2"
    ;;
    --s3-secret)
    S3_SECRET_KEY="$2"
    ;;
    --s3-region)
    S3_REGION="$2"
    ;;
    --s3-bucket)
    S3_BUCKET="$2"
    ;;
    --blazer-account-id)
    BACKBLAZE_ACCOUNT_ID="$2"
    ;;
    --blazer-key)
    BACKBLAZE_APP_KEY="$2"
    ;;
    --blazer-bucket)
    BACKBLAZE_BUCKET="$2"
    ;;
    --backup-interval)
    BACKUP_INTERVAL="$2"
    ;;
    --with-mysql)
    WITH_MYSQL="$2"
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

function usage {
    info "$0 "
}

[[ -z "${DATA_DIR}" ]] && {
  error "Required argument DATA_DIR not provided!"
}

[[ -z "${SERVER_NAME}" ]] && {
  error "Required argument SERVER_NAME not provided!"
}

[[ -z "${CONTAINER_IMAGE}" ]] && {
  error "Required argument CONTAINER_IMAGE not provided!"
}

mkdir -p ${DATA_DIR}
cd ${DATA_DIR} && DATA_DIR=$(pwd) && cd -

mkdir -p ${DATA_DIR}/mcbackup || exit 1
mkdir -p ${DATA_DIR}/worlds || exit 1
mkdir -p ${DATA_DIR}/mods || exit 1
mkdir -p ${DATA_DIR}/plugins || exit 1
mkdir -p ${DATA_DIR}/logs || exit 1
mkdir -p ${DATA_DIR}/config || exit 1
mkdir -p ${DATA_DIR}/config-server || exit 1
mkdir -p ${DATA_DIR}/logs || exit 1
mkdir -p ${DATA_DIR}/scripts || exit 1
mkdir -p ${DATA_DIR}/schematics || exit 1
mkdir -p ${DATA_DIR}/crash-reports || exit 1
mkdir -p ${DATA_DIR}/dynmap || exit 1
mkdir -p ${DATA_DIR}/nucleus || exit 1
mkdir -p ${DATA_DIR}/Flan || exit 1
mkdir -p ${DATA_DIR}/luckperms || exit 1
mkdir -p ${DATA_DIR}/orespawn || exit 1

[[ -f "${DATA_DIR}/config-server/eula.txt" ]] || {
  echo "eula=false" > "${DATA_DIR}/config-server/eula.txt"
  warning "Looks like the first run, don't forget to confirm EULA in ${DATA_DIR}/config-server/eula.txt"
  sleep 5
}

MC_HOME=/home/minecraft
SERVER_HOME=/home/minecraft/server

if [[ -f /sbin/md5 ]]; then
  MD5BIN=/sbin/md5
else
  MD5BIN=/usr/bin/md5sum
fi

[[ ! -z "$WITH_MYSQL" ]] && {
  ROOT_PASS=$(echo ${SERVER_NAME} | ${MD5BIN} | awk '{print $1}')
  if docker ps | grep "${SERVER_NAME}_mysql"; then
      MYSQL_ID=$(docker ps | grep "${SERVER_NAME}_mysql" | awk '{print $1}')
  else
      MYSQL_ID=$(docker run -d --restart=always \
      --name="${SERVER_NAME}_mysql" \
      -v ${DATA_DIR}/mysql:/var/lib/mysql \
      -e MYSQL_ROOT_PASSWORD=${ROOT_PASS} \
      -e MYSQL_USER=minecraft \
      -e MYSQL_PASSWORD=minecraft \
      -e MYSQL_DATABASE=minecraft \
      percona:5.5)
  fi

  note "Waiting database..."
  until docker exec ${MYSQL_ID} timeout 1 bash -c "cat < /dev/null > /dev/tcp/localhost/3306" > /dev/null; do
      sleep 3
  done

  WITH_MYSQL_LINK_ARG="--link=${SERVER_NAME}_mysql:db"
}

DYNMAP_PORT_ARG=""
if [[ ! -z "${DYNMAP_PORT}" ]]; then
  DYNMAP_PORT_ARG="-p ${DYNMAP_PORT}:8123"
fi

GOTTY_PORT_ARG=""
if [[ ! -z "${GOTTY_PORT}" ]]; then
  GOTTY_PORT_ARG="-p ${GOTTY_PORT}:8080"
fi

SSH_PORT_ARG=""
if [[ ! -z "${SSH_PORT}" ]]; then
  SSH_PORT_ARG="-p ${SSH_PORT}:22"
fi

SSH_PASS=${SSH_PASS-minecraft}

docker run -d --restart=always \
--name=${SERVER_NAME} ${WITH_MYSQL_LINK_ARG} \
-e MINECRAFT_AUTH_SERVER_URL=${AUTH_SERVER_URL} \
-e MC_BACKUPSCRIPTCOMPATIBLE=${MC_BACKUPSCRIPTCOMPATIBLE-true} \
-e MC_CPU_COUNT=${MC_CPU_COUNT-1} \
-e MC_INIT_MEMORY=${MC_INIT_MEMORY-1024} \
-e MC_MAX_MEMORY=${MC_MAX_MEMORY-2048} \
-e BACKUP_INTERVAL=${BACKUP_INTERVAL} \
-e S3_ACCESS_KEY=${S3_ACCESS_KEY} \
-e S3_SECRET_KEY=${S3_SECRET_KEY} \
-e S3_REGION=${S3_REGION} \
-e S3_BUCKET=${S3_BUCKET} \
-e BACKBLAZE_ACCOUNT_ID=${BACKBLAZE_ACCOUNT_ID} \
-e BACKBLAZE_APP_KEY=${BACKBLAZE_APP_KEY} \
-e BACKBLAZE_BUCKET=${BACKBLAZE_BUCKET} \
-e SSH_PASS=${SSH_PASS} \
-v ${DATA_DIR}/mcbackup:${MC_HOME}/mcbackup \
-v ${DATA_DIR}/dynmap:${SERVER_HOME}/dynmap \
-v ${DATA_DIR}/worlds:${SERVER_HOME}/worlds \
-v ${DATA_DIR}/mods:${SERVER_HOME}/mods \
-v ${DATA_DIR}/plugins:${SERVER_HOME}/plugins \
-v ${DATA_DIR}/logs:${SERVER_HOME}/logs \
-v ${DATA_DIR}/scripts:${SERVER_HOME}/scripts \
-v ${DATA_DIR}/schematics:${SERVER_HOME}/schematics \
-v ${DATA_DIR}/crash-reports:${SERVER_HOME}/crash-reports \
-v ${DATA_DIR}/Flan:${SERVER_HOME}/Flan \
-v ${DATA_DIR}/config:${SERVER_HOME}/config \
-v ${DATA_DIR}/config-server:${SERVER_HOME}/config-server \
-v ${DATA_DIR}/nucleus:${SERVER_HOME}/nucleus \
-v ${DATA_DIR}/luckperms:${SERVER_HOME}/luckperms \
-v ${DATA_DIR}/orespawn:${SERVER_HOME}/orespawn \
-p ${SERVER_PORT}:25565 \
${DYNMAP_PORT_ARG} \
${GOTTY_PORT_ARG} \
${SSH_PORT_ARG} \
${CONTAINER_IMAGE}
